services:
  service1:
    image: data-collector-svc1:latest
    environment:
      SERVICENAME: svc1
      MINDELAY: 300
      MAXDELAY: 600
      HOST: 0.0.0.0
      PORT: 1111
    ports:
      - "1111:1111"

  service2:
    image: data-collector-svc2:latest
    environment:
      SERVICENAME: svc2
      MINDELAY: 300
      MAXDELAY: 600
      HOST: 0.0.0.0
      PORT: 2222
    ports:
      - "2222:2222"

